#!/bin/sh
mkdir -p ~/.config/
## alacritty
ln -sf ~/okiami/alacritty ~/.config/alacritty
## amethyst
ln -sf ~/okiami/amethyst ~/.config/amethyst
## git
ln -sf ~/okiami/git ~/.config/git
## zsh
ln -sf ~/okiami/zsh/.zshrc ~/.zshrc
## tmux
ln -sf ~/okiami/tmux ~/.config/tmux
## nvim
ln -sf ~/okiami/nvim ~/.config/nvim
## aqua
ln -sf ~/okiami/aquaproj-aqua ~/.config/aquaproj-aqua
## mise
ln -sf ~/okiami/mise ~/.config/mise
