#!/bin/sh
mkdir -p ~/.config/
## alacritty
mkdir -p ~/.config/alacritty/
ln -sf ~/okiami/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
## amethyst
ln -sf ~/okiami/amethyst/amethyst.yml ~/.amethyst.yml
## fish
mkdir -p ~/.config/fish/
ln -sf ~/okiami/fish/ ~/.config/fish/
## git
mkdir ~/.config/git/
ln -sf ~/okiami/git/ignore ~/.config/git/ignore
## zsh
ln -sf ~/okiami/zsh/.zshrc ~/.zshrc
## tmux
mkdir -p ~/.tmux/
ln -sf ~/okiami/tmux ~/.tmux
ln -sf ~/okiami/tmux/.tmux.conf ~/.tmux.conf
## nvim
ln -sf ~/okiami/nvim ~/.config/nvim
